name: Gradle action
description: Gradle action

inputs:
  command:
    description: Run command
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        distribution: 'corretto'
        java-version: 25

    - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

    - shell: bash
      env:
        COMMAND: ${{ inputs.command }}
      run: chmod +x gradlew && ./gradlew ${COMMAND}
