name: on-merge

on:
  push:
    branches: [main]

permissions: {}

jobs:
  seed-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/gradle-action
        with:
          command: check
